version: 2  # Version of CircleCI
jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout

      - setup_remote_docker 
        
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Login to Docker
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: Build and push feed api
          command: |
            docker build -t michealgabriel/udagram-api-feed:v1 ./udagram-api-feed
            docker push michealgabriel/udagram-api-feed:v1

      - run:
          name: Build and push user api
          command: |
            docker build -t michealgabriel/udagram-api-user:v1 ./udagram-api-user
            docker push michealgabriel/udagram-api-user:v1

      - run:
          name: Build and push frontend
          command: |
            docker build -t michealgabriel/udagram-frontend:v1 ./udagram-frontend
            docker push michealgabriel/udagram-frontend:v1

      - run:
          name: Build and push reverseproxy
          command: |
            docker build -t michealgabriel/udagram-reverseproxy:v1 ./udagram-reverseproxy
            docker push michealgabriel/udagram-reverseproxy:v1